name: Github Actions Build and Deploy Lanlan
on: 
  push:
    branches:
      - master
jobs:
  lanlan-job:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout...
        uses: actions/checkout@master
      - name: Use Node.js...
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Build...
        run: |
          npm install
          npm run build
      - name: Deploy...
        uses: peaceiris/actions-gh-pages@v1.1.0
        env:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./lanlan
          publish_branch: gh-pages
